project "SDL2"
	filter "system:windows"
	kind "SharedLib"


	language "C++"
	cppdialect "C++17"

	systemversion "latest"

	vectorextensions "SSE"

	targetdir("bin/" .. outputDir .. "/%{prj.name}")
	objdir("bin-int/" .. outputDir .. "/%{prj.name}")

	includedirs { "include" }

	filter "system:windows"
		links {
			"setupapi",
			"winmm",
			"imm32",
			"version"
		}

	filter {}

	files {
		"src/audio/directsound/SDL_directsound.h",
		"src/audio/disk/SDL_diskaudio.h",
		"src/audio/dummy/SDL_dummyaudio.h",
		"src/audio/SDL_audio_c.h",
		"src/audio/SDL_audiodev_c.h",
		"src/audio/SDL_sysaudio.h",
		"src/audio/SDL_wave.h",
		"src/audio/wasapi/SDL_wasapi.h",
		"src/audio/winmm/SDL_winmm.h",
		"src/core/windows/SDL_directx.h",
		"src/core/windows/SDL_hid.h",
		"src/core/windows/SDL_windows.h",
		"src/core/windows/SDL_xinput.h",
		"src/dynapi/SDL_dynapi.h",
		"src/dynapi/SDL_dynapi_overrides.h",
		"src/dynapi/SDL_dynapi_procs.h",
		"src/events/blank_cursor.h",
		"src/events/default_cursor.h",
		"src/events/scancodes_windows.h",
		"src/events/SDL_clipboardevents_c.h",
		"src/events/SDL_displayevents_c.h",
		"src/events/SDL_dropevents_c.h",
		"src/events/SDL_events_c.h",
		"src/events/SDL_gesture_c.h",
		"src/events/SDL_keyboard_c.h",
		"src/events/SDL_mouse_c.h",
		"src/events/SDL_sysevents.h",
		"src/events/SDL_touch_c.h",
		"src/events/SDL_windowevents_c.h",
		"src/haptic/SDL_haptic_c.h",
		"src/haptic/SDL_syshaptic.h",
		"src/haptic/windows/SDL_dinputhaptic_c.h",
		"src/haptic/windows/SDL_windowshaptic_c.h",
		"src/haptic/windows/SDL_xinputhaptic_c.h",
		"src/hidapi/hidapi/hidapi.h",
		"src/hidapi/SDL_hidapi_c.h",
		"src/joystick/controller_type.h",
		"src/joystick/hidapi/SDL_hidapijoystick_c.h",
		"src/joystick/hidapi/SDL_hidapi_rumble.h",
		"src/joystick/SDL_gamecontrollerdb.h",
		"src/joystick/SDL_joystick_c.h",
		"src/joystick/SDL_sysjoystick.h",
		"src/joystick/usb_ids.h",
		"src/joystick/virtual/SDL_virtualjoystick_c.h",
		"src/joystick/windows/SDL_dinputjoystick_c.h",
		"src/joystick/windows/SDL_rawinputjoystick_c.h",
		"src/joystick/windows/SDL_windowsjoystick_c.h",
		"src/joystick/windows/SDL_xinputjoystick_c.h",
		"src/libm/math_libm.h",
		"src/libm/math_private.h",
		"src/locale/SDL_syslocale.h",
		"src/misc/SDL_sysurl.h",
		"src/power/SDL_syspower.h",
		"src/render/direct3d11/SDL_shaders_d3d11.h",
		"src/render/direct3d/SDL_shaders_d3d.h",
		"src/render/opengles2/SDL_gles2funcs.h",
		"src/render/opengles2/SDL_shaders_gles2.h",
		"src/render/opengl/SDL_glfuncs.h",
		"src/render/opengl/SDL_shaders_gl.h",
		"src/render/SDL_d3dmath.h",
		"src/render/SDL_sysrender.h",
		"src/render/SDL_yuv_sw_c.h",
		"src/render/software/SDL_blendfillrect.h",
		"src/render/software/SDL_blendline.h",
		"src/render/software/SDL_blendpoint.h",
		"src/render/software/SDL_draw.h",
		"src/render/software/SDL_drawline.h",
		"src/render/software/SDL_drawpoint.h",
		"src/render/software/SDL_render_sw_c.h",
		"src/render/software/SDL_rotate.h",
		"src/render/software/SDL_triangle.h",
		"src/SDL_assert_c.h",
		"src/SDL_dataqueue.h",
		"src/SDL_error_c.h",
		"src/SDL_hints_c.h",
		"src/SDL_internal.h",
		"src/SDL_list.h",
		"src/sensor/dummy/SDL_dummysensor.h",
		"src/sensor/SDL_sensor_c.h",
		"src/sensor/SDL_syssensor.h",
		"src/sensor/windows/SDL_windowssensor.h",
		"src/thread/SDL_systhread.h",
		"src/thread/SDL_thread_c.h",
		"src/thread/generic/SDL_syscond_c.h",
		"src/thread/windows/SDL_sysmutex_c.h",
		"src/thread/windows/SDL_systhread_c.h",
		"src/timer/SDL_timer_c.h",
		"src/video/dummy/SDL_nullevents_c.h",
		"src/video/dummy/SDL_nullframebuffer_c.h",
		"src/video/dummy/SDL_nullvideo.h",
		"src/video/khronos/vulkan/vk_icd.h",
		"src/video/khronos/vulkan/vk_layer.h",
		"src/video/khronos/vulkan/vk_platform.h",
		"src/video/khronos/vulkan/vk_sdk_platform.h",
		"src/video/khronos/vulkan/vulkan.h",
		"src/video/khronos/vulkan/vulkan.hpp",
		"src/video/khronos/vulkan/vulkan_android.h",
		"src/video/khronos/vulkan/vulkan_beta.h",
		"src/video/khronos/vulkan/vulkan_core.h",
		"src/video/khronos/vulkan/vulkan_directfb.h",
		"src/video/khronos/vulkan/vulkan_fuchsia.h",
		"src/video/khronos/vulkan/vulkan_ggp.h",
		"src/video/khronos/vulkan/vulkan_ios.h",
		"src/video/khronos/vulkan/vulkan_macos.h",
		"src/video/khronos/vulkan/vulkan_metal.h",
		"src/video/khronos/vulkan/vulkan_vi.h",
		"src/video/khronos/vulkan/vulkan_wayland.h",
		"src/video/khronos/vulkan/vulkan_win32.h",
		"src/video/khronos/vulkan/vulkan_xcb.h",
		"src/video/khronos/vulkan/vulkan_xlib.h",
		"src/video/khronos/vulkan/vulkan_xlib_xrandr.h",
		"src/video/SDL_blit.h",
		"src/video/SDL_blit_auto.h",
		"src/video/SDL_blit_copy.h",
		"src/video/SDL_blit_slow.h",
		"src/video/SDL_egl_c.h",
		"src/video/SDL_pixels_c.h",
		"src/video/SDL_rect_c.h",
		"src/video/SDL_RLEaccel_c.h",
		"src/video/SDL_shape_internals.h",
		"src/video/SDL_sysvideo.h",
		"src/video/SDL_vulkan_internal.h",
		"src/video/SDL_yuv_c.h",
		"src/video/windows/SDL_msctf.h",
		"src/video/windows/SDL_vkeys.h",
		"src/video/windows/SDL_windowsclipboard.h",
		"src/video/windows/SDL_windowsevents.h",
		"src/video/windows/SDL_windowsframebuffer.h",
		"src/video/windows/SDL_windowskeyboard.h",
		"src/video/windows/SDL_windowsmessagebox.h",
		"src/video/windows/SDL_windowsmodes.h",
		"src/video/windows/SDL_windowsmouse.h",
		"src/video/windows/SDL_windowsopengl.h",
		"src/video/windows/SDL_windowsopengles.h",
		"src/video/windows/SDL_windowsshape.h",
		"src/video/windows/SDL_windowstaskdialog.h",
		"src/video/windows/SDL_windowsvideo.h",
		"src/video/windows/SDL_windowsvulkan.h",
		"src/video/windows/SDL_windowswindow.h",
		"src/video/windows/wmmsg.h",
		"src/video/yuv2rgb/yuv_rgb.h",
		"src/video/yuv2rgb/yuv_rgb_sse_func.h",
		"src/video/yuv2rgb/yuv_rgb_std_func.h",

		"src/atomic/SDL_atomic.c",
		"src/atomic/SDL_spinlock.c",
		"src/audio/directsound/SDL_directsound.c",
		"src/audio/disk/SDL_diskaudio.c",
		"src/audio/dummy/SDL_dummyaudio.c",
		"src/audio/SDL_audio.c",
		"src/audio/SDL_audiocvt.c",
		"src/audio/SDL_audiodev.c",
		"src/audio/SDL_audiotypecvt.c",
		"src/audio/SDL_mixer.c",
		"src/audio/SDL_wave.c",
		"src/audio/winmm/SDL_winmm.c",
		"src/audio/wasapi/SDL_wasapi.c",
		"src/audio/wasapi/SDL_wasapi_win32.c",
		"src/core/windows/SDL_hid.c",
		"src/core/windows/SDL_windows.c",
		"src/core/windows/SDL_xinput.c",
		"src/cpuinfo/SDL_cpuinfo.c",
		"src/dynapi/SDL_dynapi.c",
		"src/events/SDL_clipboardevents.c",
		"src/events/SDL_displayevents.c",
		"src/events/SDL_dropevents.c",
		"src/events/SDL_events.c",
		"src/events/SDL_gesture.c",
		"src/events/SDL_keyboard.c",
		"src/events/SDL_mouse.c",
		"src/events/SDL_quit.c",
		"src/events/SDL_touch.c",
		"src/events/SDL_windowevents.c",
		"src/file/SDL_rwops.c",
		"src/filesystem/windows/SDL_sysfilesystem.c",
		"src/haptic/dummy/SDL_syshaptic.c",
		"src/haptic/SDL_haptic.c",
		"src/haptic/windows/SDL_dinputhaptic.c",
		"src/haptic/windows/SDL_windowshaptic.c",
		"src/haptic/windows/SDL_xinputhaptic.c",
		"src/hidapi/SDL_hidapi.c",
		"src/joystick/dummy/SDL_sysjoystick.c",
		"src/joystick/hidapi/SDL_hidapijoystick.c",
		"src/joystick/hidapi/SDL_hidapi_gamecube.c",
		"src/joystick/hidapi/SDL_hidapi_luna.c",
		"src/joystick/hidapi/SDL_hidapi_ps4.c",
		"src/joystick/hidapi/SDL_hidapi_ps5.c",
		"src/joystick/hidapi/SDL_hidapi_rumble.c",
		"src/joystick/hidapi/SDL_hidapi_stadia.c",
		"src/joystick/hidapi/SDL_hidapi_switch.c",
		"src/joystick/hidapi/SDL_hidapi_xbox360.c",
		"src/joystick/hidapi/SDL_hidapi_xbox360w.c",
		"src/joystick/hidapi/SDL_hidapi_xboxone.c",
		"src/joystick/SDL_gamecontroller.c",
		"src/joystick/SDL_joystick.c",
		"src/joystick/virtual/SDL_virtualjoystick.c",
		"src/joystick/windows/SDL_dinputjoystick.c",
		"src/joystick/windows/SDL_rawinputjoystick.c",
		"src/joystick/windows/SDL_windowsjoystick.c",
		"src/joystick/windows/SDL_windows_gaming_input.c",
		"src/joystick/windows/SDL_xinputjoystick.c",
		"src/libm/e_atan2.c",
		"src/libm/e_exp.c",
		"src/libm/e_fmod.c",
		"src/libm/e_log.c",
		"src/libm/e_log10.c",
		"src/libm/e_pow.c",
		"src/libm/e_rem_pio2.c",
		"src/libm/e_sqrt.c",
		"src/libm/k_cos.c",
		"src/libm/k_rem_pio2.c",
		"src/libm/k_sin.c",
		"src/libm/k_tan.c",
		"src/libm/s_atan.c",
		"src/libm/s_copysign.c",
		"src/libm/s_cos.c",
		"src/libm/s_fabs.c",
		"src/libm/s_floor.c",
		"src/libm/s_scalbn.c",
		"src/libm/s_sin.c",
		"src/libm/s_tan.c",
		"src/loadso/windows/SDL_sysloadso.c",
		"src/locale/SDL_locale.c",
		"src/locale/windows/SDL_syslocale.c",
		"src/misc/SDL_url.c",
		"src/misc/windows/SDL_sysurl.c",
		"src/power/SDL_power.c",
		"src/power/windows/SDL_syspower.c",
		"src/render/direct3d11/SDL_shaders_d3d11.c",
		"src/render/direct3d/SDL_render_d3d.c",
		"src/render/direct3d11/SDL_render_d3d11.c",
		"src/render/direct3d/SDL_shaders_d3d.c",
		"src/render/opengl/SDL_render_gl.c",
		"src/render/opengl/SDL_shaders_gl.c",
		"src/render/opengles2/SDL_render_gles2.c",
		"src/render/opengles2/SDL_shaders_gles2.c",
		"src/render/SDL_d3dmath.c",
		"src/render/SDL_render.c",
		"src/render/SDL_yuv_sw.c",
		"src/render/software/SDL_blendfillrect.c",
		"src/render/software/SDL_blendline.c",
		"src/render/software/SDL_blendpoint.c",
		"src/render/software/SDL_drawline.c",
		"src/render/software/SDL_drawpoint.c",
		"src/render/software/SDL_render_sw.c",
		"src/render/software/SDL_rotate.c",
		"src/render/software/SDL_triangle.c",
		"src/SDL.c",
		"src/SDL_assert.c",
		"src/SDL_dataqueue.c",
		"src/SDL_list.c",
		"src/SDL_error.c",
		"src/SDL_hints.c",
		"src/SDL_log.c",
		"src/sensor/dummy/SDL_dummysensor.c",
		"src/sensor/SDL_sensor.c",
		"src/sensor/windows/SDL_windowssensor.c",
		"src/stdlib/SDL_crc32.c",
		"src/stdlib/SDL_getenv.c",
		"src/stdlib/SDL_iconv.c",
		"src/stdlib/SDL_malloc.c",
		"src/stdlib/SDL_qsort.c",
		"src/stdlib/SDL_stdlib.c",
		"src/stdlib/SDL_string.c",
		"src/stdlib/SDL_strtokr.c",
		"src/thread/generic/SDL_syscond.c",
		"src/thread/SDL_thread.c",
		"src/thread/windows/SDL_syscond_cv.c",
		"src/thread/windows/SDL_sysmutex.c",
		"src/thread/windows/SDL_syssem.c",
		"src/thread/windows/SDL_systhread.c",
		"src/thread/windows/SDL_systls.c",
		"src/timer/SDL_timer.c",
		"src/timer/windows/SDL_systimer.c",
		"src/video/dummy/SDL_nullevents.c",
		"src/video/dummy/SDL_nullframebuffer.c",
		"src/video/dummy/SDL_nullvideo.c",
		"src/video/SDL_blit.c",
		"src/video/SDL_blit_0.c",
		"src/video/SDL_blit_1.c",
		"src/video/SDL_blit_A.c",
		"src/video/SDL_blit_auto.c",
		"src/video/SDL_blit_copy.c",
		"src/video/SDL_blit_N.c",
		"src/video/SDL_blit_slow.c",
		"src/video/SDL_bmp.c",
		"src/video/SDL_clipboard.c",
		"src/video/SDL_egl.c",
		"src/video/SDL_fillrect.c",
		"src/video/SDL_pixels.c",
		"src/video/SDL_rect.c",
		"src/video/SDL_RLEaccel.c",
		"src/video/SDL_shape.c",
		"src/video/SDL_stretch.c",
		"src/video/SDL_surface.c",
		"src/video/SDL_video.c",
		"src/video/SDL_vulkan_utils.c",
		"src/video/SDL_yuv.c",
		"src/video/windows/SDL_windowsclipboard.c",
		"src/video/windows/SDL_windowsevents.c",
		"src/video/windows/SDL_windowsframebuffer.c",
		"src/video/windows/SDL_windowskeyboard.c",
		"src/video/windows/SDL_windowsmessagebox.c",
		"src/video/windows/SDL_windowsmodes.c",
		"src/video/windows/SDL_windowsmouse.c",
		"src/video/windows/SDL_windowsopengl.c",
		"src/video/windows/SDL_windowsopengles.c",
		"src/video/windows/SDL_windowsshape.c",
		"src/video/windows/SDL_windowsvideo.c",
		"src/video/windows/SDL_windowsvulkan.c",
		"src/video/windows/SDL_windowswindow.c",
		"src/video/yuv2rgb/yuv_rgb.c"
	}

	defines {
		"DLL_EXPORT",
		"_WINDOWS"
	}
	filter "configurations:Debug"
		defines {
			"_DEBUG"
		}

		buildoptions {
			"/Z7",
			"/Ob1",
			"/ZI",
			"/Od",
			"/GS-",
			"/W3"
		}

		linkoptions {
			"/DEBUG",
			"/NODEFAULTLIB"
		}

		runtime "Debug"
		symbols "On"
	
	filter "configurations:Release"
		defines {
			"NDEBUG"
		}
		buildoptions {
			"/Zi",
			"/Ob1",
			"/ZI",
			"/GS-",
			"/W3"
		}
		linkoptions {
			"/DEBUG",
			"/NODEFAULTLIB",
			"/OPT:ICF",
			"/OPT:REF"
		}
		runtime "Release"
		optimize "On"
